export const categoryMeta = {
  fishermen: {
    label: "Fishermen",
    tagline: "The towers that defend the dock.",
    gradient: "bg-gradient-grey",
  },
  fish: {
    label: "Fish",
    tagline: "Threats swimming in from the deep.",
    gradient: "bg-gradient-blue",
  },
  mechanics: {
    label: "Mechanics",
    tagline: "Gambling magic and other systems that bend the tides.",
    gradient: "bg-gradient-cyan",
  },
};

export const wikiEntries = [
  // fishermen
  {
    id: crypto.randomUUID(),
    category: "fishermen",
    title: "Fisherman",
    description: "A grizzled veteran with a steady cast. Reliable single-target damage at medium range.",
    stats: { damage: 10, range: 188, type: "range", cost: 100 },
    tags: ["starter", "single-target", "medium-range"],
    rarity: "common",
    image: "/images/rybak.png",
  },
  {
    id: crypto.randomUUID(),
    category: "fishermen",
    title: "Net Caster",
    description: "Casts weighted nets that catch groups of fish.",
    stats: { damage: 15, range: 84, type: "melee", cost: 140},
    tags: ["melee", "crowd-control"],
    rarity: "rare",
    image: "/images/meleTower.png",
  },
  {
    id: crypto.randomUUID(),
    category: "fishermen",
    title: "Harpoon Angler",
    description: "A precision marksman whose harpoons hit enemies at a distance.",
    stats: { damage: 50, range: 384, type: "sniper", cost: 200, capacity: 9 },
    tags: ["sniper", "long-range", "elite"],
    rarity: "legendary",
    image: "/images/sniper.png",
  },

  // fih
  {
    id: crypto.randomUUID(),
    category: "fish",
    title: "Roach",
    description: "The first wave of the swarm. Weak and small.",
    stats: { hp: 20, speed: "normal", bounty: 5, damage: 2 },
    tags: ["early-wave", "weak"],
    rarity: "common",
    image: "/images/plotka.png",
  },
  {
    id: crypto.randomUUID(),
    category: "fish",
    title: "Catfish",
    description: "Heavy fih that spawns another fish when killed.",
    stats: { hp: 280, speed: "slow", bounty: 23, damage: 20, spawn: "Roach, Electric Eel"},
    tags: ["tank", "spawner"],
    rarity: "uncommon",
    image: "/images/sum.png",
  },
  {
    id: crypto.randomUUID(),
    category: "fish",
    title: "Sturgeon",
    description: "Strong and dangerous enemy that spawns another fish when killed.",
    stats: { hp: 420, speed: "slow", armor: 10, bounty: 25, spawn: "Cods" },
    tags: ["elite", "spawner", "armored"],
    rarity: "legendary",
    image: "/images/jesiotr.png",
  },
  {
    id: crypto.randomUUID(),
    category: "fish",
    title: "Electric Eel",
    description: "Super fast.",
    stats: { hp: 30, speed: "fast", bounty: 10, damage: 5 },
    tags: ["fast"],
    rarity: "rare",
    image: "/images/wegorz.png",
  },
  {
    id: crypto.randomUUID(),
    category: "fish",
    title: "Cod",
    description: "Strong armored Cod.",
    stats: { hp: 65, speed: "normal", armor: 5.5, damage: 8, bounty: 8 },
    tags: ["strong", "armored"],
    rarity: "uncommon",
    image: "/images/dorsz.png",
  },

  // mechanics
  {
    id: crypto.randomUUID(),
    category: "mechanics",
    title: "Magic",
    description: "Roll 1d6. On 6, all fish on screen take 200 damage. On 1, your gold halves.",
    stats: { cost: 50, cooldown: "20s", risk: "high" },
    tags: ["gamble", "burst"],
    rarity: "uncommon",
    image: "/images/dice-of-fortune.jpg",
  },
];